export const ActivitiesIcons = {
  fortum: {
    addresschange: '/Fortum/addresschange_oEQtmnlfx9.svg',
    insurance: '/Fortum/insurance_UZL41alqR8.svg',
    homecleaningoffer: '/Fortum/hemstadning_GLrIEbRrK.svg',
    familylaw: '/Fortum/familylaw_XSfb2gRyTY.svg',
    handyman: '/Fortum/handyman_kr7QqanG7.svg',
    alarmservice: '/Fortum/hemlarm_LYeVaePZV.svg',
    internet: '/Fortum/broadband_8r0v8Iteo.svg',
    movehelpCombined: '/Fortum/movehelp_EABY2Kb7Z.svg',
    painting: '/Fortum/painting_I-67i7zNe.svg',
    mail: '/Fortum/mail_xMQu1W8hL.svg',
    loan: '/Fortum/loan_8YcEhhxeF.svg',
    alarm: '/Fortum/hemlarm_LYeVaePZV.svg',
    tv: '/Fortum/Fortum_TV_76ANu9YeO.svg',
    school: '/Fortum/school_LJJ0MkHpU.svg',
    parking: '/Fortum/parking_ntAiQWsOw.svg',
    waste: '/Fortum/Fortum_Trash_i68Z_rZ20.svg',
    gas: '/Fortum/gas_TNp8BJ0iX.svg',
    heat: '/Fortum/Fortum_Heating_NXAaB9L1r.svg',
    water: '/Fortum/Fortum_Water_TntNxmXL6.svg',
    moveclean: '/Fortum/cleaning_dZ8D8-n8h.svg',
    movehelp: '/Fortum/move_-SvFfYlvS.svg',
    diy: '/Fortum/diy_aYEd3GnUPE.svg',
    electricity: '',
    power: '',
    transportation: '/Fortum/move_-SvFfYlvS.svg',
    transportationChecklist: '/Fortum/move_-SvFfYlvS.svg',
  },
  normal: {
    addresschange: '/Common/Addresschange_new_wfU_gle-V.svg',
    insurance: '/Common/Insurance_new_s4siMfSOoh.svg',
    homecleaningoffer: '/Common/Cleaning_new_Mrf-43onJ.svg',
    familylaw: '/Common/Legal_new_XGtwUdtia.svg',
    handyman: '/Common/Handyman_new_z5pGX2R3-.svg',
    alarmservice: '/Common/Alarm_new_O-H1mOy14.svg',
    internet: '/Common/Broadband_new_3cCspN6bV.svg',
    movehelpCombined: '/Common/Move_help_new_PtPweqWxS.svg',
    painting: '/Common/painting_llRhtbhjK.svg',
    mail: '/Common/Mail_new_y7nf7H5Ru.svg',
    loan: '/Common/Mortgage_new_RSptL2HvY.svg',
    alarm: '/Common/Security_new_8AYa2uyTS.svg',
    tv: '/Common/TV_Telephony_new_o5Ml218Zi.svg',
    school: '/Common/School_new_xT529Pd9IP.svg',
    parking: '/Common/Parking_new_-7qRARlow.svg',
    waste: '/Common/Trash_new_85EpDvylEm.svg',
    gas: '/Common/Energy_new_Tr4IFpJvR.svg',
    heat: '/Common/Heating_new_tfBxvxCpWW.svg',
    water: '/Common/Water_new_Qc0Nsxyd6.svg',
    moveclean: '/Common/Cleaning_new_Mrf-43onJ.svg',
    movehelp: '/Common/Move_help_new_PtPweqWxS.svg',
    diy: '/Common/Handyman_new_z5pGX2R3-.svg',
    electricity: '/Common/Electricity.svg',
    power: '/Common/Electricity.svg',
    homefix: '/Common/Handyman_new_z5pGX2R3-.svg',
    transportation: '/Common/Transportation_new_62BDA4k_Mt.svg',
    transportationChecklist: '/Common/Transportation_new_62BDA4k_Mt.svg',
  },
  fb: {
    addresschange: '/Common/Addresschange_new_wfU_gle-V.svg',
    insurance: '/Common/Insurance_new_s4siMfSOoh.svg',
    homecleaningoffer: '/Common/Cleaning_new_Mrf-43onJ.svg',
    familylaw: '/Common/Legal_new_XGtwUdtia.svg',
    handyman: '/Common/Handyman_new_z5pGX2R3-.svg',
    alarmservice: '/Common/Alarm_new_O-H1mOy14.svg',
    internet: '/Common/Broadband_new_3cCspN6bV.svg',
    movehelpCombined: '/Common/Move_help_new_PtPweqWxS.svg',
    painting: '/Common/painting_llRhtbhjK.svg',
    mail: '/Common/Mail_new_y7nf7H5Ru.svg',
    loan: '/Common/Mortgage_new_RSptL2HvY.svg',
    alarm: '/Common/Security_new_8AYa2uyTS.svg',
    tv: '/Common/TV_Telephony_new_o5Ml218Zi.svg',
    school: '/Common/School_new_xT529Pd9IP.svg',
    parking: '/Common/Parking_new_-7qRARlow.svg',
    waste: '/Common/Trash_new_85EpDvylEm.svg',
    gas: '/Common/Energy_new_Tr4IFpJvR.svg',
    heat: '/Common/Heating_new_tfBxvxCpWW.svg',
    water: '/Common/Water_new_Qc0Nsxyd6.svg',
    moveclean: '/Common/Cleaning_new_Mrf-43onJ.svg',
    movehelp: '/Common/Move_help_new_PtPweqWxS.svg',
    diy: '/Common/Handyman_new_z5pGX2R3-.svg',
    electricity: '/Common/Electricity.svg',
    power: '/Common/Electricity.svg',
    homefix: '/Common/Handyman_new_z5pGX2R3-.svg',
    transportation: '/Common/Transportation_new_62BDA4k_Mt.svg',
    transportationChecklist: '/Common/Transportation_new_62BDA4k_Mt.svg',
  },
}

export type IconsUrls = {
  addresschange: string
  insurance: string
  homecleaningoffer: string
  familylaw: string
  handyman: string
  alarmservice: string
  internet: string
  movehelpCombined: string
  painting: string
  mail: string
  loan: string
  alarm: string
  tv: string
  school: string
  parking: string
  waste: string
  gas: string
  heat: string
  water: string
  moveclean: string
  movehelp: string
  diy: string
  power: string
  electricity: string
}
