const ServiceUrlEnum = {
  ADDRESSCHANGE: 'addresschange',
  DIY: 'flyttkartonger',
  MOVEHELP: 'movehelp?product=moving',
  MOVECLEAN: 'movehelp?product=cleaning',
  MOVEHELP_COMBINED: 'movehelp',
  INTERNET: 'internet',
  BROADBAND: 'broadband',
  POWER: 'electricity',
  ELECTRICITY: 'electricity',
  INSURANCE: 'insurance',
  HOMEALARM: 'hemlarm',
  HOMECLEANING: 'hemstadning',
  MOVEHELP_NEW: 'movehelp',
  MOVECLEAN_NEW: 'moveclean',
  EXTERNAL_MOVEHELP: 'flytthjalp',
  EXTERNAL_MOVECLEAN: 'flyttstadning',
  ACTIVITES: 'activites',
  RENOVATE: 'renovate',
  ASSEMBLY: 'assembly',
  WINDOWCLEANING: 'windowcleaning',
  SHOWCLEANING: 'showcleaning',
  DECLARATION: 'declaration',
  PACKAGING: 'packaging',
  MOVEHELPABROAD: 'movehelpabroad',
  DECEASEDESTATE: 'deceasedestate',
  STORAGE: 'storage',
  REMOVAL: 'removal',
  MOVEHELPEXPRESS: 'movehelpexpress',
  HOMECLEAN: 'homeclean',
}

export default ServiceUrlEnum
