// Document API Error Codes
export const DOCUMENT_ERROR_CODES = {
  // Claude API Errors
  CLAUDE_OVERLOADED: 'CLAUDE_OVERLOADED',
  CLAUDE_TIMEOUT: 'CLAUDE_TIMEOUT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  CLAUDE_API_ERROR: 'CLAUDE_API_ERROR',

  // File Validation Errors
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_IMAGE_FORMAT: 'INVALID_IMAGE_FORMAT',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',

  // Document Validation Errors
  NO_SIGNERS_FOUND: 'NO_SIGNERS_FOUND',
  NO_ONE_HAS_SIGNED: 'NO_ONE_HAS_SIGNED',
  INCOMPLETE_SIGNATURES: 'INCOMPLETE_SIGNATURES',
  MISSING_PERSONAL_NUMBERS: 'MISSING_PERSONAL_NUMBERS',
  NO_VALID_SIGNATURES: 'NO_VALID_SIGNATURES',
  WAITING_FOR_MORE_PAGES: 'WAITING_FOR_MORE_PAGES',

  // Processing Errors
  FAILED_TO_PROCESS: 'FAILED_TO_PROCESS',
  FAILED_TO_EXTRACT_INFO: 'FAILED_TO_EXTRACT_INFO',
  DOCUMENT_ANALYSIS_FAILED: 'DOCUMENT_ANALYSIS_FAILED',

  // Client-side Errors
  TIMEOUT: 'TIMEOUT',
  NO_RESULT: 'NO_RESULT',
  API_CONFIG_ERROR: 'API_CONFIG_ERROR',
} as const

export type DocumentErrorCode = (typeof DOCUMENT_ERROR_CODES)[keyof typeof DOCUMENT_ERROR_CODES]

// Helper to get all error codes as an array
export const KNOWN_ERROR_CODES = Object.values(DOCUMENT_ERROR_CODES)
