import { ThemeEnum } from '@/common/enums/ThemeEnum'

export enum IconEnum {
  ELECTRICITY_SIMPLE = 'ELECTRICITY_SIMPLE',
  POWER = 'POWER',
  ELECTRICITY_FLOW_1 = 'ELECTRICITY_FLOW_1',
  ELECTRICITY_FLOW_2 = 'ELECTRICITY_FLOW_2',
  ADDRESSCHANGE = 'ADDRESSCHANGE',
  ADDRESSCHANGE_SIMPLE = 'ADDRESSCHANGE_SIMPLE',
  BROADBAND_SIMPLE = 'BROADBAND_SIMPLE',
  INTERNET = 'INTERNET',
  BROADBAND_GROUP_DEAL = 'BROADBAND_GROUP_DEAL',
  MOVEHELP = 'MOVEHELP',
  MOVECLEAN = 'MOVECLEAN',
  MOVEHELPCOMBINED = 'MOVEHELPCOMBINED',
  TWO_FINGER_ICON = 'TWO_FINGER_ICON',
  HOUSE = 'HOUSE',
  INFO_ICON = 'INFO_ICON',
  MOVING_ARROW_ICON = 'MOVING_ARROW_ICON',
  CALENDAR_ICON = 'CALENDAR_ICON',
  CALENDAR_ICON_CIRCLE = 'CALENDAR_ICON_CIRCLE',
  PUZZLE_ICON = 'PUZZLE_ICON',
  CONTACT_AVATAR = 'CONTACT_AVATAR',
  COMPUTER_WOMAN = 'COMPUTER_WOMAN',
  BROADBAND_WIFI_ICON = 'BROADBAND_WIFI_ICON',
  BROADBAND_ROUTER_ICON = 'BROADBAND_ROUTER_ICON',
  BROADBAND_WIFI_WITH_ARROW_ICON = 'BROADBAND_WIFI_WITH_ARROW_ICON',
  SHOWCLEANING = 'SHOWCLEANING',
  INSURANCE = 'INSURANCE',
  HOUSE_LARGE = 'HOUSE_LARGE',
}

export const THEME_ASSETS: Record<ThemeEnum, Record<IconEnum, string>> = {
  fb: {
    ELECTRICITY_SIMPLE: '/icons/fb/electricity/Electricity_simple.svg',
    POWER: '/icons/fb/electricity/Electricity_circle.svg',
    ELECTRICITY_FLOW_1: '',
    ELECTRICITY_FLOW_2: '',
    ADDRESSCHANGE_SIMPLE: '/icons/fb/addresschange/Addresschange_simple.svg',
    ADDRESSCHANGE: '/icons/fb/addresschange/Addresschange_circle.svg',
    BROADBAND_SIMPLE: '/icons/fb/broadband/Broadband_simple.svg',
    INTERNET: '/icons/fb/broadband/Broadband_circle.svg',
    BROADBAND_WIFI_ICON: '',
    BROADBAND_WIFI_WITH_ARROW_ICON: '',
    BROADBAND_ROUTER_ICON: '',
    BROADBAND_GROUP_DEAL: '',
    MOVEHELP: '/icons/fb/movehelp/Movehelp_circle.svg',
    MOVECLEAN: '/icons/fb/moveclean/Moveclean_circle.svg',
    MOVEHELPCOMBINED: '/icons/fb/movehelp/Movehelp_circle.svg',
    TWO_FINGER_ICON: '',
    HOUSE: '',
    INFO_ICON: '/icons/fb/common/info_icon_fb.svg',
    MOVING_ARROW_ICON: '',
    CALENDAR_ICON: '/icons/fb/common/CalendarBlank.svg',
    CALENDAR_ICON_CIRCLE: '/icons/fb/common/CalendarBlank.svg',
    PUZZLE_ICON: '',
    CONTACT_AVATAR: '',
    COMPUTER_WOMAN: '',
    SHOWCLEANING: '/icons/fb/showcleaning/showcleaning_fb_circle.svg',
    INSURANCE: '',
    HOUSE_LARGE: '',
  },
  fortum: {
    ELECTRICITY_SIMPLE: '/icons/flyttsmart/electricity/Electricity.svg',
    POWER: '/icons/flyttsmart/electricity/Electricity.svg',
    ELECTRICITY_FLOW_1: '/icons/flyttsmart/electricity/Electricity.svg',
    ELECTRICITY_FLOW_2: '/icons/flyttsmart/electricity/Electricity.svg',
    ADDRESSCHANGE_SIMPLE: '/icons/flyttsmart/addresschange/Addresschange.svg',
    ADDRESSCHANGE: '/icons/flyttsmart/addresschange/Addresschange.svg',
    MOVING_ARROW_ICON: '/icons/flyttsmart/addresschange/movingArrow.svg',
    BROADBAND_SIMPLE: '/icons/flyttsmart/broadband/Broadband.svg',
    INTERNET: '/icons/flyttsmart/broadband/Broadband.svg',
    BROADBAND_WIFI_ICON: '/icons/flyttsmart/broadband/Wifi-Icon.svg',
    BROADBAND_WIFI_WITH_ARROW_ICON: '/icons/flyttsmart/broadband/Wifi-With-Arrow.svg',
    BROADBAND_ROUTER_ICON: '/icons/flyttsmart/broadband/Router.svg',
    BROADBAND_GROUP_DEAL: '/icons/flyttsmart/broadband/group_deal_image.svg',
    MOVEHELP: '/icons/flyttsmart/movehelp/Movehelp_circle.svg',
    MOVECLEAN: '/icons/flyttsmart/moveclean/Moveclean_circle.svg',
    MOVEHELPCOMBINED: '/icons/flyttsmart/movehelp/Movehelp_circle.svg',
    TWO_FINGER_ICON: '✌️',
    HOUSE: '/icons/flyttsmart/electricity/house.svg',
    INFO_ICON: '/icons/flyttsmart/common/info_icon_flyttsmart.svg',
    CALENDAR_ICON: '/icons/flyttsmart/common/Calendar.svg',
    CALENDAR_ICON_CIRCLE: '/icons/flyttsmart/common/Calendar_circle.svg',
    PUZZLE_ICON: '/icons/flyttsmart/common/Puzzle_icon.svg',
    CONTACT_AVATAR: '/icons/flyttsmart/common/ContactAvatar.svg',
    COMPUTER_WOMAN: '/icons/flyttsmart/broadband/Computer_woman.svg',
    SHOWCLEANING: '',
    INSURANCE: '/icons/flyttsmart/insurance/insurance.svg',
    HOUSE_LARGE: '/icons/flyttsmart/insurance/house_large.svg',
  },
  normal: {
    ELECTRICITY_SIMPLE: '/icons/flyttsmart/electricity/Electricity.svg',
    POWER: '/icons/flyttsmart/electricity/Electricity.svg',
    ELECTRICITY_FLOW_1: '/icons/flyttsmart/electricity/Electricity.svg',
    ELECTRICITY_FLOW_2: '/icons/flyttsmart/electricity/Electricity.svg',
    ADDRESSCHANGE_SIMPLE: '/icons/flyttsmart/addresschange/Addresschange.svg',
    ADDRESSCHANGE: '/icons/flyttsmart/addresschange/Addresschange.svg',
    MOVING_ARROW_ICON: '/icons/flyttsmart/addresschange/movingArrow.svg',
    BROADBAND_SIMPLE: '/icons/flyttsmart/broadband/Broadband.svg',
    INTERNET: '/icons/flyttsmart/broadband/Broadband.svg',
    BROADBAND_WIFI_ICON: '/icons/flyttsmart/broadband/Wifi-Icon.svg',
    BROADBAND_WIFI_WITH_ARROW_ICON: '/icons/flyttsmart/broadband/Wifi-With-Arrow.svg',
    BROADBAND_ROUTER_ICON: '/icons/flyttsmart/broadband/Router.svg',
    BROADBAND_GROUP_DEAL: '/icons/flyttsmart/broadband/group_deal_image.svg',
    MOVEHELP: '/icons/flyttsmart/movehelp/Movehelp_circle.svg',
    MOVECLEAN: '/icons/flyttsmart/moveclean/Moveclean_circle.svg',
    MOVEHELPCOMBINED: '/icons/flyttsmart/movehelp/Movehelp_circle.svg',
    TWO_FINGER_ICON: '✌️',
    HOUSE: '/icons/flyttsmart/electricity/house.svg',
    INFO_ICON: '/icons/flyttsmart/common/Question_green.svg',
    CALENDAR_ICON: '/icons/flyttsmart/common/Calendar.svg',
    CALENDAR_ICON_CIRCLE: '/icons/flyttsmart/common/Calendar_circle.svg',
    PUZZLE_ICON: '/icons/flyttsmart/common/Puzzle_icon.svg',
    CONTACT_AVATAR: '/icons/flyttsmart/common/ContactAvatar.svg',
    COMPUTER_WOMAN: '/icons/flyttsmart/broadband/Computer_woman.svg',
    SHOWCLEANING: '',
    INSURANCE: '/icons/flyttsmart/insurance/insurance.svg',
    HOUSE_LARGE: '/icons/flyttsmart/insurance/house_large.svg',
  },
}

export type IconsUrls = {
  ADDRESSCHANGE: string
  INTERNET: string
  POWER: string
  MOVECLEAN: string
  MOVEHELP: string
  MOVEHELPCOMBINED: string
}
