const UserMock = {
  contact: {
    email: 'test@test.se',
    emailVerified: false,
    phone: '+46707554433',
  },
  currentMove: {
    addressStatus: 'ready' as 'loading' | 'ready' | 'empty',
    addresschange: {
      completedAt: null,
      state: 'not_started',
    },
    diy: {
      completedAt: null,
      contractData: {
        additionalProducts: null,
        cancelExistingContract: false,
        endDate: null,
        existingProvider: '',
        groupDealChosen: false,
        offerId: 'tre-mobilt-bredband-med-4g-minirouter-1',
        selectedFlatNr: '',
        sessionId: '54f3b5a4-c0fd-4ba4-81d9-9f3e879135ba',
        startDate: '2022-06-03',
      },
      lockedAt: null,
      meta: null,
      provider: null,
      skippedAt: null,
      startedAt: '2022-06-03T07:22:38.719Z',
      state: 'started',
      canceledAt: null,
    },
    apartmentType: 'owned',
    checklist: ['alarmservice', 'painting'],
    createdAt: '2022-04-28T10:10:26.967Z',
    fromAddress: {
      apartmentNumber: '123',
      city: '11120',
      street: 'Vasagatan 22',
      zip: '11120',
    },
    fromResidenceSize: 100,
    id: 'f644cd44-dca6-4527-b00d-a8372395ea22',
    insurance: {
      completedAt: '2022-06-03T08:11:02.669Z',
      contractData: {
        email: 'test@test.se',
        existingProvider: 'Trygg-Hansa',
        keepExistingProvider: true,
        phone: '+46707554433',
      },
      lockedAt: null,
      meta: null,
      provider: 'existing',
      skippedAt: null,
      startedAt: '2022-06-03T08:11:02.542Z',
      state: 'completed',
      canceledAt: null,
    },
    internet: {
      completedAt: null,
      contractData: {
        additionalProducts: null,
        cancelExistingContract: false,
        endDate: null,
        existingProvider: '',
        groupDealChosen: false,
        offerId: 'tre-mobilt-bredband-med-4g-minirouter-1',
        selectedFlatNr: '',
        sessionId: '54f3b5a4-c0fd-4ba4-81d9-9f3e879135ba',
        startDate: '2022-06-03',
      },
      lockedAt: null,
      meta: null,
      provider: 'tre',
      skippedAt: null,
      startedAt: '2022-06-03T07:22:38.719Z',
      state: 'started',
      canceledAt: null,
    },
    meta: {
      alarmServiceOrders: [
        {
          totalPrice: '13690',
          contactInfo: { address: 'Vasagatan 11, 11120 Stockholm', email: 'test@test.se', fullName: 'Förnamn Efternamn', phoneNumber: '+46707554433' },
          deliveryDate: '2022-06-08',
          alarmServiceProducts: [
            { name: 'Rörelsedetektor', price: '990', quantity: 1 },
            { name: 'Magnetkontakt', price: '590', quantity: 1 },
            { name: 'Brandvarnare med rökdetektor', price: '1290', quantity: 1 },
            { name: 'Vattendetektor', price: '1290', quantity: 1 },
            { name: 'Ringklocka med videokamera', price: '2990', quantity: 1 },
            { name: 'Akustisk glaskrossdetektor', price: '1290', quantity: 1 },
            { name: 'Scenarioknappar', price: '790', quantity: 1 },
            { name: 'Multidetektor', price: '1690', quantity: 1 },
            { name: 'Temperatur- och fuktåtergivare', price: '1290', quantity: 1 },
            { name: 'Smartplug', price: '790', quantity: 1 },
            { name: 'Simkort', price: '50 kr/mån', quantity: 1 },
            { name: 'Uppgradering: Stöd för Z-Wave', price: '690', quantity: 1 },
            { name: 'Fria väktarutryckingar', price: '100 kr/mån', quantity: 1 },
          ],
        },
      ],
      hasSentTechBuddyNotification: true,
    },
    movehelp: {
      canceledAt: null,
      completedAt: '2022-06-01T08:33:44.230Z',
      contractData: {
        address: 'Vasagatan 11',
        date: '2022-06-29',
        flyttsmartNotes: '',
        fromAddressResidenceInfo: {
          elevator: null,
          floor: 0,
          isAdditionalSpace: true,
        },
        heavyLifting: false,
        isOtherInformation: 'no',
        materialPrice: 2500,
        moveCleanPrice: 123,
        moveHelpPrice: 0,
        otherInformation: '',
        packagingPrice: 25,
        price: 2700,
        residenceSize: 100,
        rut: false,
        service: 'cleaning',
        storagePrice: 25,
        time: '18:30',
        toAddressResidenceInfo: {
          elevator: null,
          floor: 0,
          isAdditionalSpace: true,
        },
        transportCost: 27,
        wantsHandyman: true,
        wantsPackaging: true,
        wantsStorage: true,
      },
      declinedAt: null,
      lockedAt: '2022-05-30T08:43:46.879Z',
      meta: null,
      provider: 'fungerande_flytt_ab',
      reportedAt: null,
      skippedAt: null,
      startedAt: '2022-05-16T12:09:15.744Z',
      state: 'completed',
    },
    moveclean: {
      canceledAt: null,
      completedAt: null,
      contractData: {
        service: 'cleaning',
        residenceSize: 55,
        date: '2022-12-23',
        moveCleanDate: '2022-12-23',
        price: 3000,
        isOtherInformation: 'no',
        wantsHandyman: true,
        wantsPackaging: true,
        wantsStorage: true,
        fromAddressResidenceInfo: {
          floor: 0,
          isAdditionalSpace: 'no',
          residenceType: 'house',
        },
      },
      declinedAt: null,
      lockedAt: null,
      meta: null,
      provider: 'zimpelt_flyttochstad',
      reportedAt: null,
      skippedAt: null,
      startedAt: '2022-12-20T12:43:05.399Z',
      state: 'started',
    },
    movehelpCombined: {
      canceledAt: null,
      completedAt: null,
      contractData: null,
      declinedAt: null,
      lockedAt: null,
      meta: null,
      provider: null,
      reportedAt: null,
      skippedAt: null,
      startedAt: null,
      state: 'not_started',
    },
    movingDate: '2022-06-30',
    power: {
      completedAt: null,
      contractData: {
        cancelExistingContract: true,
        contractName: 'Tibber Rörligt pris',
        discountPeriod: 0,
        endDate: '2022-06-03',
        estimatedYearlyConsumption: 3411,
        startDate: '2022-06-03',
      },
      lockedAt: null,
      meta: null,
      provider: 'tibber',
      skippedAt: null,
      startedAt: '2022-05-06T07:34:19.401Z',
      state: 'started',
      canceledAt: null,
    },
    residenceSize: 66,
    residenceType: 'apartment',
    toAddress: {
      apartmentNumber: '1234',
      city: 'Stockholm',
      street: 'Vasagatan 11',
      zip: '11120',
      residenceType: 'apartment',
      apartmentType: 'renting',
      residenceSize: 77,
    },
    updatedAt: '2022-06-03T10:46:44.265Z',
    wizardDone: false,
  },
  currentMoveLoading: false,
  leadDetails: null,
  inviter: undefined,
  domesticServicesBalance: {
    data: {
      amountRemaining: { amount: 75000, limitedForRotServices: 50000 },
      amountUsed: {
        rot: 0,
        rut: 0,
      },
      updatedAt: '2022-12-12T14:43:10.384Z',
    },
    isBankIdLoading: false,
  },
  hasFetchedData: true,
  profile: {
    createdAt: '2022-04-28T10:10:26.287Z',
    firstName: 'Förnamn',
    fullName: 'Förnamn Efternamn',
    id: 'f3ad9f43-7e04-400f-bfb3-e022ef0736a9',
    intercomHash: '72061e530f36b2eb6b54027973882af30ae9c82846250ebea4fff0e4368e5601',
    lastName: 'Efternamn',
    meta: null,
    email: 'test+dev@flyttsmart.se',
    phone: '+46000000000',
    partnerDetails: {
      agentName: 'Johan',
      partnerId: 'b6af4553-4bae-4050-8637-120864efd666',
      partnerName: 'Johansson',
    },
    leadDetails: { sourceSystem: '', brokerOfficeId: 'b6af4553-4bae-4050-8637-120864efd666', brokerOfficeName: '', type: '', brokerOfficePersonName: 'Test Broker' },
    pno: '199204056611',
    updatedAt: '2022-04-28T10:10:26.287Z',
  },
}
export default UserMock
