// Generated from /partner logos assets
export const partnerLogos = [
  { src: '/images/partners/all/37a6a99b-02be-4ed9-982d-293d57406519-logo-rbq6dryhs.png', alt: '37a6a99b 02be 4ed9 982d 293d57406519 logo' },
  { src: '/images/partners/all/3etagee-i03mmm4nz.svg', alt: '3etagee' },
  { src: '/images/partners/all/alicia-edelman-1-1-sig6fpo1p.svg', alt: 'Alicia Edelman (1) 1' },
  { src: '/images/partners/all/br-5fa3fe4a84d0b100084bd69b-hagerstens-maklare-juxs3lsx9.png', alt: 'BR 5fa3fe4a84d0b100084bd69b Hagerstens Maklare' },
  { src: '/images/partners/all/br-6041b2626c02e80008a1f7fb-wallenberg-fastighetsformedling-h60cevzsj.png', alt: 'BR 6041b2626c02e80008a1f7fb Wallenberg Fastighetsformedling' },
  { src: '/images/partners/all/br-60ba0cd1923f790008d5f42d-bocentrum-i-filipstad-8gz6rx5so.png', alt: 'BR 60ba0cd1923f790008d5f42d Bocentrum i Filipstad' },
  { src: '/images/partners/all/behrer-t5olod1hj.png', alt: 'Behrer' },
  { src: '/images/partners/all/brobergmakleri-2hccinrve.png', alt: 'BrobergMakleri' },
  { src: '/images/partners/all/casafastighetsformedling-zxnaoqqtyf.png', alt: 'CasaFastighetsformedling' },
  { src: '/images/partners/all/edward-logga-svart-2-rader-muebbwqji.png', alt: 'Edward logga Svart 2 rader' },
  { src: '/images/partners/all/edward-logo-mi5yjp1j1.svg', alt: 'Edward logo' },
  { src: '/images/partners/all/fastighetsbyran-logo-pobmqvfiy.svg', alt: 'Fastighetsbyran logo' },
  { src: '/images/partners/all/gorengs-nw-o2ukhj.png', alt: 'Gorengs nW' },
  { src: '/images/partners/all/hh-logo-staplad-pos-obestruken-cmyk-v7-msmdld-8-v.png', alt: 'HH logo staplad pos obestruken CMYK v7 MSmdLd 8 v' },
  { src: '/images/partners/all/historiska-hem-logo-ri0m3fw-x.svg', alt: 'Historiska Hem logo rI0M3Fw x' },
  { src: '/images/partners/all/innerstad-logo-2-orvndkd-n.png', alt: 'Innerstad logo 2 OrVNdkd N' },
  { src: '/images/partners/all/ivy-green-cmyk-c.jpg', alt: 'Ivy green CMYK C' },
  { src: '/images/partners/all/lf-fastighet-logo-blue-1-h2-pwg053.png', alt: 'LF Fastighet logo blue 1 H2' },
  { src: '/images/partners/all/lisa-lavii-logo-mork-ulzagdrg.png', alt: 'LISA LAVII LOGO MORK' },
  { src: '/images/partners/all/lejons-makleri-logo-njpe-l-5m.svg', alt: 'Lejons Makleri Logo nJPE l 5M' },
  { src: '/images/partners/all/maklarhuset-logotyp-1wwxhjgay.svg', alt: 'Maklarhuset logotyp' },
  { src: '/images/partners/all/more-xebcbplx4u.png', alt: 'More' },
  { src: '/images/partners/all/nyva-fastighetsformedling-yfyrpvzn28.svg', alt: 'NYVA Fastighetsformedling' },
  { src: '/images/partners/all/nomad-y9lbsllzp.png', alt: 'Nomad' },
  { src: '/images/partners/all/notar-new-4g0mb9fuo.svg', alt: 'Notar new' },
  { src: '/images/partners/all/oscarss-uou5iih-d.png', alt: 'Oscarss UoU5iiH D' },
  { src: '/images/partners/all/reveny-vgjjpcqeo.png', alt: 'Reveny' },
  { src: '/images/partners/all/sthlmfast-logo-9nndlwcswl.svg', alt: 'STHLMFast logo' },
  { src: '/images/partners/all/simon-crest-eax4df1yo.svg', alt: 'Simon Crest' },
  { src: '/images/partners/all/valvet-uag4hmg6y.png', alt: 'Valvet' },
  { src: '/images/partners/all/warberg-x6hya241n.png', alt: 'Warberg' },
  { src: '/images/partners/all/ahmanmakleri-ifgrm2syu.svg', alt: 'ahmanmakleri' },
  { src: '/images/partners/all/individia-ksqjxtdgs.svg', alt: 'individia' },
  { src: '/images/partners/all/lansforsakring-hjpt2jmho.png', alt: 'lansforsakring' },
  { src: '/images/partners/all/loga-lang-70htd6ozc.png', alt: 'loga lang' },
  { src: '/images/partners/all/logo-2-yqud6fovx.png', alt: 'logo (2)' },
  { src: '/images/partners/all/logo-b-ctot4o1sc.svg', alt: 'logo b' },
  { src: '/images/partners/all/maklarhuset-og-image.webp', alt: 'maklarhuset og image' },
  { src: '/images/partners/all/nedladdning-4-zdq1yij2p.png', alt: 'nedladdning (4)' },
  { src: '/images/partners/all/stadshem-logotyp-black-png-v2phosrd.png', alt: 'stadshem logotyp black png' },
  { src: '/images/partners/all/tibber.jpeg', alt: 'tibber' },
]
